spring.application.name=ff-inventory-service

server.port=9092

#DataSource cfg
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=ATG_CATFEED
spring.datasource.password=Sk1llnet

#JPA_Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.cloud.openfeign.cache.enabled=false

management.endpoints.web.exposure.include=health,info,metrics


# Eureka client (service discovery)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Feign client (to call OMS)
feign.hystrix.enabled=true

# Resilience4j Circuit Breaker + Retry
resilience4j.circuitbreaker.instances.omsService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.omsService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.omsService.failureRateThreshold=50

resilience4j.retry.instances.omsService.maxAttempts=3
resilience4j.retry.instances.omsService.waitDuration=2s