spring.application.name=ff-oms-integration-service
server.port=9091

# Eureka client (service discovery)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#DataSource cfg
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=ATG_CATFEED
spring.datasource.password=Sk1llnet

#JPA_Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics